"""Drift detection between clu's bundled skills and the installed copies.

`scan()` is the whole surface: it reads `~/.claude/skills/<name>/SKILL.md` for
each bundled skill and returns one `SkillStatus` per skill. It prints nothing,
writes nothing, and decides no policy — three callers need the same facts and
three different behaviours (doctor reports; `clu init` and `clu queue add`
repair), so detection, policy and formatting are separate layers.

Two properties are separate on purpose:

* **placement** is what is actually on disk. It is decided with `is_symlink()`
  BEFORE `exists()`, because `exists()` follows the link and reports a dangling
  symlink as "nothing installed". A read that raises is `unreadable`, never
  silently treated as in sync.
* **writable** is whether clu may safely write that path — a filesystem
  property, not a name. A target is unsafe when the leaf OR any parent
  component is a symlink, because a write then resolves into a directory clu
  does not own. Note the parent case: for `~/.claude/skills/plan/SKILL.md` the
  symlink is usually the *directory*, so a leaf-only check calls it writable
  when it is not. The walk goes to the filesystem root — a symlinked `~` or
  `~/.claude` is the same hazard one level up.

* **provenance** is whether clu wrote the installed bytes. It is a MEMBERSHIP
  test over two sources, never an equality test against one: the install
  record clu keeps in its own config dir, and `skills_manifest.json` — the
  fingerprints of every SKILL.md version clu has released. One hash could only
  ever say "differs"; two sources can tell an old clu copy apart from a hand
  edit, which is the question a repair path has to answer. A copy installed
  before the record existed is recognized by the manifest; a copy written by a
  clu newer than the manifest is recognized by the record.

One `SKILL.md` per skill is the packaged unit (`pyproject.toml` ships
`skills/*/SKILL.md` and nothing else), so this compares that one file rather
than walking the directory. `tests/test_skill_sync.py` asserts the invariant.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path
from typing import Literal

from . import db

# What is on disk at the target path.
#   file       — a regular file, no symlink anywhere on its path to it
#   link       — the SKILL.md itself is a symlink that resolves
#   absent     — nothing there
#   broken     — a symlink whose destination does not exist
#   unreadable — something is there, but its bytes could not be read
Placement = Literal["file", "link", "absent", "broken", "unreadable"]

# How the installed bytes compare to the bundled copy. `unknown` means there
# were no bytes to compare (absent / broken / unreadable), never "same".
Content = Literal["in_sync", "differs", "unknown"]

# Who wrote the installed bytes.
#   recognized — matches clu's install record, or a version clu shipped
#   foreign    — installed, matches neither: somebody edited it
#   absent     — no bytes to attribute (absent / broken / unreadable), which is
#                exactly the set for which `content` is `unknown`
Provenance = Literal["recognized", "foreign", "absent"]

SKILL_FILENAME = "SKILL.md"

# Bounded because `repair()` runs on `clu init` and `clu queue add`. The write
# is a handful of rows and only clu contends for it, so a wait this long
# already means something is wrong. Failing beats hanging an operator command.
RECORD_LOCK_TIMEOUT_S = 5.0

# Ships in the package beside the skills themselves; regenerated by a human
# with `scripts/gen_skill_manifest.py`. Module-level so a test can point the
# loader at a name that does not exist.
MANIFEST_FILENAME = "skills_manifest.json"

# clu's own record of what it last wrote lives in the `skills` table of the
# host database. It never goes inside a SKILL.md: a per-install stamp in the
# file would make the installed copy differ from the bundled one by
# construction, so every skill would report drift forever.


@dataclass(frozen=True)
class SkillStatus:
    """One skill's installed state. Facts only — no policy, no formatting."""

    name: str
    target: Path
    placement: Placement
    content: Content
    writable: bool
    provenance: Provenance


def installed_path(name: str) -> Path:
    """Where clu installs `name`: `~/.claude/skills/<name>/SKILL.md`."""
    return Path.home() / ".claude" / "skills" / name / SKILL_FILENAME


def bundled_bytes(name: str) -> bytes:
    """The bundled `SKILL.md` for `name`, as shipped in the package."""
    return files("end_of_line").joinpath(f"skills/{name}/{SKILL_FILENAME}").read_bytes()


def is_writable_target(target: Path) -> bool:
    """False when the leaf or ANY parent component is a symlink.

    `Path.resolve()` is deliberately not used: it collapses the very
    distinction being tested. Each component is checked with `is_symlink()`,
    which is false for a component that does not exist yet — an install into a
    path clu will create is safe.
    """
    if target.is_symlink():
        return False
    return not any(parent.is_symlink() for parent in target.parents)


def digest(data: bytes) -> str:
    """The fingerprint used everywhere here: lowercase hex SHA-256 of the raw
    bytes on disk. NOT a git blob id — `git hash-object` prepends a
    NUL-terminated `blob <len>` header before hashing, so a blob id can never
    equal a hash of the same bytes, and a manifest built from blob ids matches
    nothing while looking perfectly well-formed."""
    return hashlib.sha256(data).hexdigest()


def load_manifest() -> tuple[dict[str, list[str]], str | None]:
    """The shipped fingerprints, plus a reason string when they are unusable.

    ABSENT and UNREADABLE are different conditions and must not collapse into
    one. A missing manifest is the documented degradation — a wheel built
    without it in `package-data`, or a clu older than the manifest — and
    recognition correctly falls back to the install record alone. A manifest
    that is PRESENT but corrupt is a defect, and it fails in the worst
    direction available: every copy clu itself wrote reads as `foreign`, so
    doctor tells the operator their untouched file is a local edit and repair
    declines to touch it. Silent in both directions unless someone says so,
    which is what the reason string is for.
    """
    try:
        raw = files("end_of_line").joinpath(MANIFEST_FILENAME).read_text()
    except OSError:
        return {}, None  # absent — the documented, correct degradation
    try:
        data = json.loads(raw)
    except ValueError as exc:
        return {}, f"not valid JSON ({exc})"
    if not isinstance(data, dict):
        return {}, f"expected a JSON object, found {type(data).__name__}"
    good: dict[str, list[str]] = {}
    dropped: list[str] = []
    for name, hashes in data.items():
        if isinstance(name, str) and isinstance(hashes, list):
            good[name] = [h for h in hashes if isinstance(h, str)]
        elif isinstance(name, str):
            dropped.append(name)
    if dropped:
        return good, f"unreadable entries for {', '.join(sorted(dropped))}"
    return good, None


def shipped_fingerprints() -> dict[str, list[str]]:
    """Every SKILL.md version clu has released, name -> hex digests.

    Degrades to `{}` rather than raising; `load_manifest()` is the variant that
    also reports WHY when the answer is empty.
    """
    return load_manifest()[0]


def installed_record() -> dict[str, str]:
    """What clu last wrote, name -> hex digest.

    An absent, locked, or newer-schema host database reads as `{}`. This is a
    cache of clu's own writes, not durable data — losing it degrades
    recognition to the manifest, which is a smaller feature, not a wrong
    answer.
    """
    try:
        with db.host_conn() as conn:
            rows = conn.execute("SELECT name, digest FROM skills").fetchall()
    except db.DEGRADABLE_ERRORS:
        return {}
    return dict(rows)


def record_install(name: str, digest: str) -> None:
    """Remember that clu wrote `digest` for `name`.

    One transaction — see `_record_installs`, which does the work for one
    skill and for a whole `repair()` run alike.
    """
    _record_installs([(name, digest)])


def _record_installs(pairs: Iterable[tuple[str, str]]) -> None:
    """Remember a whole batch of writes in ONE transaction.

    A single `BEGIN IMMEDIATE` rather than a row at a time: two clu processes
    can reach here at once — a `clu queue add` repairing a skill while a `clu
    install-skill` runs — and a half-applied batch would leave some skills
    recorded and others not, which silently turns the unrecorded ones foreign.

    Batched rather than one call per skill because `repair()` runs at every
    `clu init` and `clu queue add`: taking the write lock once per updated
    skill is affordable for the rare explicit install and not for a path on
    those two commands.

    The wait is BOUNDED for the same reason: hanging `clu queue add` with no
    output is worse than the degraded answer below, and worse than the
    failed-refresh case the caller already handles. On timeout this raises
    `db.DbBusy` — a `RuntimeError`, NOT an `OSError`, so a caller guarding
    only `OSError` will not catch it.

    Losing the record is a real but narrow degradation, not the trap it looks
    like: the bytes just written equal the bundled copy, whose hash is in the
    shipped manifest, so the next scan still reads them `recognized` through
    that route. It bites only where the manifest cannot help — an editable
    install carrying uncommitted skill edits — and there the next repair sees
    `foreign` and refuses until the record is writable again.
    """
    rows = list(pairs)
    if not rows:
        return
    with db.host_conn(timeout_s=RECORD_LOCK_TIMEOUT_S) as conn:
        with db.write_txn(conn, timeout_s=RECORD_LOCK_TIMEOUT_S) as cur:
            cur.executemany("INSERT OR REPLACE INTO skills (name, digest) VALUES (?, ?)", rows)


def _provenance(
    name: str,
    installed: bytes | None,
    record: dict[str, str],
    manifest: dict[str, list[str]],
) -> Provenance:
    """Membership across BOTH sources, keyed by skill name.

    Never an equality test against the record alone: a user running two clu
    versions against one home gets a record from the newer and a manifest from
    the older, and either one on its own would call the other's copy foreign.
    """
    if installed is None:
        return "absent"
    d = digest(installed)
    if record.get(name) == d or d in manifest.get(name, ()):
        return "recognized"
    return "foreign"


def _classify(name: str, target: Path) -> tuple[Placement, Content, bytes | None]:
    """Placement, content and the installed bytes for one target.

    `is_symlink()` before `exists()`. The bytes come back so the caller can
    fingerprint them without a second read — a re-read would also let the file
    change between the comparison and the hash.
    """
    link = target.is_symlink()
    if link and not target.exists():
        return "broken", "unknown", None
    if not link and not target.exists():
        return "absent", "unknown", None
    try:
        installed = target.read_bytes()
    except OSError:
        # Permissions, a directory where a file belongs, an I/O error. The
        # previous check swallowed this and reported the skill as in sync.
        return "unreadable", "unknown", None
    same = installed == bundled_bytes(name)
    return ("link" if link else "file"), ("in_sync" if same else "differs"), installed


def scan(names: Iterable[str] | None = None) -> list[SkillStatus]:
    """Classify each named skill's installed copy. Defaults to every bundled
    skill, in `BUNDLED_SKILLS` order. Read-only: creates no directories."""
    # Imported here rather than at module scope: cli imports this module.
    from .cli import BUNDLED_SKILLS

    if names is None:
        names = BUNDLED_SKILLS
    else:
        # Validate up front so an unbundled name fails the SAME way whether or
        # not something happens to be installed at its path. Without this the
        # bundled read raises only when the installed read succeeded first,
        # which makes a caller's typo look like a filesystem problem.
        names = list(names)
        unknown = [n for n in names if n not in BUNDLED_SKILLS]
        if unknown:
            raise ValueError(f"not bundled clu skills: {', '.join(sorted(unknown))}")
    # Both provenance sources are read once per scan, not once per skill.
    record = installed_record()
    manifest = shipped_fingerprints()
    out: list[SkillStatus] = []
    for name in names:
        target = installed_path(name)
        placement, content, installed = _classify(name, target)
        out.append(
            SkillStatus(
                name=name,
                target=target,
                placement=placement,
                content=content,
                writable=is_writable_target(target),
                provenance=_provenance(name, installed, record, manifest),
            )
        )
    return out


@dataclass(frozen=True)
class RepairResult:
    """What `repair()` wrote, and what it declined to touch.

    `refused` is `(name, reason)`; the reason is one of:

    * `foreign` — the bytes match no version clu ever shipped, so somebody
      edited them. Reported rather than silently skipped: overwriting is the
      one thing repair must never do here, and a skipped edit the operator
      never hears about is how they end up believing a stale skill is current.
    * `symlink` — a symlink on the target's path (or a dangling one where the
      skill should be). clu will not write through one, and will not "warn and
      write anyway" either.
    * `unreadable` — the installed bytes could not be read, so there is
      nothing to compare and nothing to attribute.
    """

    updated: list[str]
    refused: list[tuple[str, str]]


def repair(names: Iterable[str] | None = None) -> RepairResult:
    """Bring every recognized, writable installed skill up to the bundled copy.

    Two gates, both necessary, neither sufficient:

    * `provenance == "recognized"` — clu wrote these bytes, so replacing them
      loses nothing. A `foreign` copy holds somebody's edit and is reported.
    * `writable` — no symlink anywhere on the path. Keyed on the filesystem
      property, never on `placement`: the symlink is usually the skill
      DIRECTORY, which leaves the leaf a regular file reading `placement ==
      "file"`, so a placement-keyed guard never fires on the shape this exists
      to refuse.

    Nothing installed is nothing to repair — this refreshes, it does not
    install, so `absent` is silent rather than a finding. An in-sync copy is
    silent too, whatever else is true of it: nothing is being skipped.

    Writes are atomic per file and the sidecar is written ONCE for the whole
    run. If a write raises, the skills already written are still recorded on
    the way out — an unrecorded write reads as `foreign` next time, which
    would make repair refuse its own output forever.
    """
    written: list[tuple[str, str]] = []
    updated: list[str] = []
    refused: list[tuple[str, str]] = []
    try:
        for s in scan(names):
            if s.placement == "absent" or s.content == "in_sync":
                continue
            if s.placement == "broken":
                refused.append((s.name, "symlink"))
                continue
            if s.placement == "unreadable":
                refused.append((s.name, "unreadable"))
                continue
            if not s.writable:
                refused.append((s.name, "symlink"))
                continue
            if s.provenance != "recognized":
                refused.append((s.name, "foreign"))
                continue
            payload = bundled_bytes(s.name)
            if not _write_atomic(s.target, payload):
                refused.append((s.name, "symlink"))
                continue
            written.append((s.name, digest(payload)))
            updated.append(s.name)
    finally:
        if written:
            _record_installs(written)
    return RepairResult(updated=updated, refused=refused)


def _write_atomic(target: Path, payload: bytes) -> bool:
    """Replace `target`'s bytes in one step. False when the path became unsafe.

    `os.replace` onto the leaf, never unlink-then-write: it leaves no window
    in which the file is absent, and onto a symlinked leaf it replaces the
    LINK rather than writing through to whatever it points at.

    The write-safety re-check lives here because `scan()` computed `writable`
    earlier and the filesystem can change in between — and it has to precede
    `mkstemp`, not merely `os.replace`: `mkstemp(dir=...)` inside a symlinked
    parent has already written into the directory clu was refusing to touch.

    `dir=` is not optional. Without it the temp file lands in the system temp
    dir, which is a different filesystem from `~` on plenty of setups, and
    `os.replace` across filesystems raises.
    """
    if not is_writable_target(target):
        return False
    fd, tmp_name = tempfile.mkstemp(
        prefix=target.name + ".",
        suffix=".tmp",
        dir=str(target.parent),
    )
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(payload)
            fh.flush()
            os.fsync(fh.fileno())
        os.replace(tmp_name, target)
    except Exception:
        try:
            os.unlink(tmp_name)
        except FileNotFoundError:
            pass
        raise
    return True
